version: "3"

services:

  redis:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"

#  bot:
#    container_name: telegram-bot
#    build: .
#    restart: always
#    env_file:
#      - .env
#    links:
#      - postgres
#      - redis
#    depends_on:
#      - postgres
#      - redis

volumes:
  postgres-data:
  redis-data: